return {
  -- Note: this is a plugin I'm developing to learn more about nvim
  --{
  --  "lvauthrin/chatgpt.nvim",
  --  dir = os.getenv("HOME") .. "/code/chat-gpt.nvim",
  --  dev = true,
  --  cmd = "ChatGPT",
  --  --enabled = false,
  --  config = function(_, _)
  --    require("chatgpt").setup({ api_key = os.getenv("OPENAI_API_KEY") })
  --  end,
  --},
  -- TODO: Re-enable if copilot does not work well
  --{
  --  "jackMort/ChatGPT.nvim",
  --  dependencies = {
  --    "MunifTanjim/nui.nvim",
  --    "nvim-lua/plenary.nvim",
  --    "nvim-telescope/telescope.nvim",
  --  },
  --  opts = {
  --    keymaps = {
  --      -- NOTE: This is needed because the default mapping <C-cr> does not work
  --      submit = "<C-s>",
  --    },
  --  },
  --  config = function(_, opts)
  --    print(vim.inspect(opts))
  --    require("chatgpt").setup(opts)
  --  end,
  --  lazy = false,
  --},
}
